# Header
menu:
  blog: /blog/

# Content
excerpt_link: Read More

# Sidebar
sidebar: bottom
widgets:
  - category
  - archive
  - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
  - category
  - archive
  - recent_posts

# widget behavior
archive_type: "monthly"
show_count: true

# Miscellaneous
twitter: wwwanyuchang
